### ISSUE TITLE
Software u2f support

### ISSUE THREAD

**Issue by ys** [kryptco/krypton-ios#100]
Any plans on supporting software u2f so that we can use krypto also for u2f auth?

**Comment by agrinman** [comment]
@ys it's something we want to do, but we're not sure when -- currently we're diving deep into developer tools like SSH + Git. We're working to understand if this would be valuable for our users. Do you have an enterprise use case for this or personal use? Would love to hear more about your use case at `hello@krypt.co`. Thanks!
