### ISSUE TITLE
Source Tree Push notifications

### ISSUE THREAD

**Issue by Esity** [kryptco/krypton-ios#105]
Hey guys, 

Currently using Krypton on iOS and my Mac for development. I have Krypton tied to my BitBucket account which works great. Finally decided to start up source tree to push a few things and noticed that it is sending dozens of approvals. I know this is technically by design for both Krypton and Source Tree but not sure what I can do to silence this other then using a separate key for Source Tree
![fullsizeoutput_33c0](https://user-images.githubusercontent.com/1851830/35753702-62754318-0826-11e8-8e0f-234c27eb8840.jpeg)

**Comment by agrinman** [comment]
@Esity There's a way to turn off SourceTree auto git-fetch: `SourceTree > Preferences > Check default remotes for X minutes`. You can make the interval longer or just disable this useless (IMO) feature.

**Comment by Esity** [comment]
@agrinman I am just trying to think if there is a better way to accomplish this. I know I can turn it off. Wasn't sure if there was a better work around

**Comment by agrinman** [comment]
@Esity Got it. I think you need to decide if you want to know/approve every access to bitbucket or not. If you want persistent sync you should probably use a separate local key for this purpose as you suggested. You can also keep both your Krypton key and a local key on bitbucket, but change your SSH config to prefer the local key on your computer.

**Comment by Esity** [comment]
Closing this
