### ISSUE TITLE
"Cannot connect to the Internet"

### ISSUE THREAD

**Issue by eblot** [kryptco/krypton-ios#106]
For some reason (DHCP slow?) when Krypton is started from a notification while the phone is asleep, a popup sometimes shows up with a "Cannot connect to Internet" message *while* any other app may access the Internet. 

I suspect Krypton is faster to test the connection than the phone is to obtain an access to the Internet when connected to some enterprise WiFi network.

It would be no trouble if the popup had a "Try again" button - but unfortunately it had not, only an abort or Settings button to reach the connection settings that need no change.

Once this popup is closed, there is no immediate option (but kill the SSH request on the host side and restart a new SSH connection) to obtain a new authorisation request to show up on Krypton UI.

**Comment by agrinman** [comment]
@eblot Thanks for the bug report, the dialogue should definitely try a few times before it complains. It might have actually already received the SSH request but then it thinks the internet access fell so it drops it. This is something I'll need to dig into a bit more. 

Have you enabled bluetooth/push notifications for Krypton?

**Comment by eblot** [comment]
> Have you enabled bluetooth/push notifications for Krypton?
In Settings/Krypton, Allow Notifications are enabled, and Bluetooth sharing and Background App refresh are also enabled - I'm not sure if it answers your question?

**Comment by agrinman** [comment]
thanks, I was just making sure you're able to approve requests without opening the app via push/ble

**Comment by agrinman** [comment]
closing -- i believe this issue was fix in a recent release, please re-open if still present
