### ISSUE TITLE
Unable to pair with Chrome's Krypton Authenticator

### ISSUE THREAD

**Issue by ken5scal** [kryptco/krypton-ios#111]
Everytime I tried to pair iPhone Krypton App with Krypton Authenticator in the Chrome App, it fails.
Android app is on the other hand, succeeds.

Version: 2.4.2677

**Comment by agrinman** [comment]
U2F functionality was introduced in Krypton iOS version 2.5.0, please update and let me know if it still doesn't work! Thanks.

**Comment by ken5scal** [comment]
ic, let me try it out
