### ISSUE TITLE
Issue with Google Smart Lock

### ISSUE THREAD

**Issue by daenney** [kryptco/krypton-ios#115]
I can't use Krypton with Google Smart Lock, preventing me from logging in on iOS devices. During the process Smart Lock pops up a notification asking if I want to open Krypton (to handle the U2F bits), so I said "Open App". Krypton shows the authentication request, I accept it, but then instead of popping back into Smart Lock it opens Safari which just results in a 400 Error from Google.

I also have a bluetooth U2F token from Feitian that I could use but once I've told Smart Lock it can open Krypton I can't stop that from happening, preventing me from using the bluetooth token. Reinstalling Smart Lock didn't help resetting that flow.

**Comment by daenney** [comment]
Turns out it also doesn't work in Safari itself either. If i go to accounts.google.com, do the whole procedure, eventually it'll open Krypton, I'll OK the request and then bam back in Safari it opens a new tab and 400 again.

**Comment by kcking** [comment]
Sorry for the inconvenience. If you ever need to revert to normal Smart Lock behavior, uninstalling Krypton and restarting your phone will reset which apps handle the u2f app-link.

Are you by any chance logging in in an incognito tab?

**Comment by daenney** [comment]
Unfortunately uninstalling Krypton also means losing my GPG and SSH keys.

Not using an incognito tab no. I managed to work around it by having Smart Lock accept a backup code in the mean time, but it would be great to figure out what's going wrong in the interaction here. It seems to almost work!

**Comment by agrinman** [comment]
@daenney are you trying to login to smart lock with Krypton? This is not currently supported -- only logging in to iOS settings and logging in with safari is currently supported. We're working on adding support for Chrome iOS and Smart Lock (if possible).

**Comment by agrinman** [comment]
We updated this blog post with setup instructions: https://krypt.co/blog/posts/use-google-advanced-protection-with-krypton.html#setup-instructions

Please re-open this issues if you're still facing issues!

**Comment by rknall** [comment]
HI. I tried to follow these instructions, but it fails. Upon accepting the request in Krypton a message appears "Unknown error "noKnownKeyHandle"". I recently switched phones, and besides a lot of other issues, this is the only one remaining. I can use the login for other services though (Github, Gitlab working fine).

**Comment by hugo** [comment]
@kcking, since upgrading to iOS 13, Smart Lock no longer prompts to open Krypton when following [the instructions](https://krypt.co/blog/posts/use-google-advanced-protection-with-krypton.html#setup-instructions) and instead asks to pair a bluetooth device:
![IMG_1077](https://user-images.githubusercontent.com/1704089/65388190-ac03fa80-dd43-11e9-96a4-46f190d5a859.jpg)
