### ISSUE TITLE
"The incoming request was invalid" if krypton app not open 

### ISSUE THREAD

**Issue by kingishb** [kryptco/krypton-ios#118]
👋 Apologies if this is a duplicate, and I really love krypton btw! 

When logging into AWS I see the following error unless I explicitly open the app. EDIT: this is actually happening on all services for me now.

 I've tried re-pairing with the browser but to no avail. Happy to provide any other info if you think it's helpful. 
<img width="294" alt="screen shot 2019-02-20 at 8 40 14 am" src="https://user-images.githubusercontent.com/3827393/53103595-2ab56280-34eb-11e9-9dff-8d62584f1ece.png">

**Comment by agrinman** [comment]
I believe this was fixed in an update a few months ago. Please re-open if still present.
