### ISSUE TITLE
badLogBlockHash, try again

### ISSUE THREAD

**Issue by benmoss** [kryptco/krypton-ios#119]
Not sure if this is a client or a server problem.

```
Request failed.

The incoming request was invalid. badLogBlockHash. Please try again
```

I've been getting this error whenever I use Krypton with Git. It seems to not matter however, I get the regular confirmation push notification after that and everything still works.

**Comment by agrinman** [comment]
Are you on krypton teams by chance?

**Comment by benmoss** [comment]
I had it enabled, but I don't think this key was associated with the team.
