### ISSUE TITLE
Question: Is Apple Watch supported?

### ISSUE THREAD

**Issue by a-stankevich** [kryptco/krypton-ios#122]
Given that Zero-Touch is disabled is it possible to control login process with Apple Watch?
Or even more, is it possible to store all secrets, including SSH keys on Apple Watch?

**Comment by agrinman** [comment]
Yes -- approving logins from the watch should work automatically. watchOS simply mirrors notifications on the iOS, there's no separate Krypton software at the moment that runs on the watch itself.
