### ISSUE TITLE
iOS: Turning off 'Show approved notifications' does not stop Approved notifications

### ISSUE THREAD

**Issue by shanewilson** [kryptco/krypton-ios#75]
Not sure what info you need but:

iPhone 7
iOS 10.3.3
Kryptonite v2.2.0

I set *When to ask for approval?* to `never` and *Show approved notifications?* to `off` but still get a constant stream of *Approved request from ... SSH Login* anytime I interact with my git repo.

**Comment by agrinman** [comment]
@shanewilson unfortunately this feature has some caveats due to some limitations of iOS notifications: see more here https://github.com/kryptco/kryptonite-ios/issues/38. Thanks for the issue, we need to explain this better in Kryptonite.

**Comment by BenGale** [comment]
There wasn't really a solution in #38 though, you closed it?

**Comment by agrinman** [comment]
@BenGale there's a "best effort" solution that was pushed in the last release, but I agree calling this a solution was too optimistic. If the Kryptonite app is terminated from the background by the system or the user, `kr` goes ahead and sends a "remote push" which triggers some background code to handle to request.  The downside is that reliability is that iOS then requires a notification to be shown regardless.

**Comment by BenGale** [comment]
Is there anyway to make the app continue to work with notifications turned off? For example my main machine is set to allow and not notify, if its all I'm using I'd be able to turn notifications off. Currently that seems to break everything.

**Comment by agrinman** [comment]
@BenGale Yes, if the app is in the foreground you can auto (or manually) approve requests. If the app is in the background, you can off notifications *through the  iOS notification settings* but now the app depends on bluetooth LE to work properly.

**Comment by BenGale** [comment]
I find that when I do that the app no longer approves requests.

**Comment by agrinman** [comment]
@BenGale one way to quickly test if bluetooth is working is to put your phone on airplane mode (with bluetooth turned on) and see if requests work with the app **open**, if not you might need to toggle bluetooth on both mac/iphone. Bluetooth is a really wonky thing unfortunately.

**Comment by mastohhh** [comment]
Did you try a Background Update Notification ? https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH10-SW8

The JSON Payload is like that : 

```
{
    "aps" : {
        "content-available" : 1
    }
}
```

I see in your project : https://github.com/kryptco/kr/ in your file [aws.go](https://github.com/kryptco/kr/blob/2a9566c075f5396b0232418df284e3f7dab98c42/aws.go) two methods : `PushAlertToSNSEndpoint` and `PushToSNSEndpoint`

The second one should be the good one. The setting _Show approved notifications_ should be stored on server side so the good push method should be used ?

**Comment by shanewilson** [comment]
I had to give the app access to `Bluetooth Sharing` but it finally works for me with notifications turned off.

**Comment by agrinman** [comment]
As of Krypton 2.4.4, this should finally be fixed now! 

It's not 100% perfect: your screen might light up occasionally **but** no sound and no vibrations and at most only one "Krypton Request" might appear even if lots of auth requests are going through. 

Please let us know if you an experience anything different than the above!

**Comment by allanchau** [comment]
@agrinman This seems to still be an issue for me, I get repeat `Krypton Request` notifications every few minutes. Version 2.5.7.726.799d54
